Revert "Add support for dependent bindable properties."
This reverts commit 2dc087b58747f726413ac62bd0b6fd43c1835a8f.


I believe this broke the Android Studio build:

tools/adt/idea/android/src/com/android/tools/idea/lang/databinding/model/PsiModelMethod.java:25: error: PsiModelMethod is not abstract and does not override abstract method getBindableAnnotation() in ModelMethod
public class PsiModelMethod extends ModelMethod {

Change-Id: Ia714f58a68a3d677e0f92cb01b4ac755bb28f2af